### PR TITLE
Send an action when the radio button group's value changes

### PR DESCRIPTION
**Pull request by philpee2**
@igillis @thangdinh @Addepar/uie

### CODE REVIEW

**Comment by Dylnuge** [comment]
:+1: LGTM

**Comment by thangdinh** [comment]
LGTM2

**Comment by cyril-sf** [comment]
Tests??

**Comment by philpee2** [comment]
@cyril-sf Discussed with @Dylnuge, and we agreed that testing this is pretty much just testing Ember internals.

**Comment by cyril-sf** [comment]
I disagree. You add a new API, that is now untested.

**Comment by philpee2** [comment]
To be fair, the entire radio button group component is untested. 

We can add some tests for it, although I'm not sure how to go about it. In the meantime, the functionality will be tested on the Iverson side.

**Pull request merged**
