### PR TITLE
Fix selected cells in color picker

### PR DESCRIPTION
**Pull request by LydiaBarnes**
The selected color cell now correctly triggers as active in the dropdown, which highlights with a border.
Before:
active-cell-broken
After:
active-cell-fixed

The transparent icon shows up properly in the picker button when transparent is selected.
Before:
transparent-cell-broken
After:
transparent-cell-fixed

Note on tests:
I am not able to run tests locally right now so I'm not sure if tests pass or not, going to run them here instead for now.
UPDATE:
Had to set `karma-qunit` to version `1.0.0` to get tests working.

### CODE REVIEW

**Comment by LydiaBarnes** [comment]
@Addepar/fire

**Comment by thangdinh** [comment]
Add the resolutions as suggested to get the tests passed, @LydiaBarnes

**Comment by LydiaBarnes** [comment]
retest

**Comment by LydiaBarnes** [comment]
@Addepar/fire tests finally passing 🌈 , please review

**Comment by shiller-addepar** [comment]
**LGTM** but you need to use release-it to bump up the patch version before merging.  I can lend a hand, but some instructions are in the repo's readme.

**Pull request merged**
