### PR TITLE
do not execute insert callback if destroying

### PR DESCRIPTION
**Pull request by joseph-chu**
In some cases, particularly in test, if a modal is spawned and then clicked too quickly, the modal will no longer exist by the time Ember attempts to execute the `didInsertElement` callback, resulting in an error.

@cyril-sf

### CODE REVIEW

**Comment by joseph-chu** [comment]
Fixed commented code @Dylnuge @philpee2

**Comment by philpee2** [comment]
Code still looks commented to me?

**Comment by joseph-chu** [comment]
let's pretend that didn't happen

**Comment by cyril-sf** [comment]
LGTM

**Pull request closed without merging**
