### PR TITLE
Don't reset query on multi-select selection change

### PR DESCRIPTION
**Pull request by azirbel**
@thangdinh @liuyang-li @igillis 

Do you know why we had this line in the first place? Is it the behavior we want?

@Addepar/ui2-developers

### CODE REVIEW

**Comment by azirbel** [comment]
@joseph-chu what do you think of this fix?

**Comment by thangdinh** [comment]
I don't know why it was there in the first place. But I just saw that behavior and would like to get rid of it too. For multi select, I think we should only clear the query text whenever the dropdown is hidden. In our case here, the dropdown is always hidden between selections, which is not efficient. I am fixing it in my PR. Thanks.
LGTM

**Comment by liuyang-li** [comment]
LGTM2. Is it gonna be hard to add a test?

**Comment by cyril-sf** [comment]
This is part of the first commit of the repo :smile: 

+ 1 for a test

**Comment by azirbel** [comment]
I will definitely write a test here; just wanted to see if anyone had objections to this change.

**Comment by joseph-chu** [comment]
I'm a little suspicious of the underlying pattern that caused this to happen in the first place (a change to the DOM was made during click propagation, leading to some failure somewhere) but this fixes it as well as any other change so it looks fine to me.

**Comment by azirbel** [comment]
I've added a very simple unit test here and don't plan to do more within ember-widgets. Ideally I think we should have a functional test that makes sure the selectable items aren't re-rendered when you make a selection ... but then, I also think ideally we should take a good look at the selection handling here, because it doesn't look that great to me. (Use of an observer is a big red flag).

This change fixes a bug in our main app - I'll write a more specific test there.

Let me know if you're ok with this PR as-is.

**Comment by cyril-sf** [comment]
If you revert your change, does the test break?

**Comment by azirbel** [comment]
Yes.

**Comment by cyril-sf** [comment]
LGTM

**Pull request merged**
